---
name: ci
on:
  pull_request:
  push:
    branches:
      - 'release/**'
jobs:
  yamllint:
    uses: networkservicemesh/.github/.github/workflows/yamllint.yaml@main

  shellcheck:
    uses: networkservicemesh/.github/.github/workflows/shellcheck.yaml@main

  golangci-lint:
    uses: networkservicemesh/.github/.github/workflows/golangci-lint.yaml@main

  exclude-fmt-errorf:
    uses: networkservicemesh/.github/.github/workflows/exclude-fmt-errorf.yaml@main

  checkgomod:
    uses: networkservicemesh/.github/.github/workflows/checkgomod.yaml@main

  azure:
    environment: AKS
    name: Azure Kubernetes Service
    runs-on: ubuntu-latest
    steps:
      - name: Set up azure permissions
        run: |
          sudo chmod -R 777 ~/.azure
      - name: Set up /bin permissions
        run: |
          sudo chmod -R 777 /bin
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
      - name: Run tests
        working-directory: ${{ github.repository }}
        run: |
          go test -count 1 -timeout 1h55m -race -v ./... -parallel 4
        env:
          KUBECONFIG: /tmp/config
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs-${{ github.run_number }}
          path: ${{ github.repository }}/logs
